### PR TITLE
Fixes app compatibility for Play Store

### PR DESCRIPTION
**Pull request by txmiker**
changes feature to required=false to fix the 0 device compatibility for Google Play Store.
MR

### CODE REVIEW

**Comment by vbier** [comment]
Are the changes to app.iml and build.gradle needed? I do not want to have a new version number commited for every update you do on the play store if not needed. You could just leave these changes in your local clone.

**Comment by txmiker** [comment]
I would think a snapshot recorded of what was used for releases to the play store.  I would suggest commit and create a 0.9.91pre tag.  May then want to update the .gitignore, suggest looking at https://github.com/github/gitignore/blob/master/Android.gitignore for other options?  Your call of course.

**Comment by vbier** [comment]
Sorry, I do not understand what you are trying to tell me. 
Do you need a new version number in the gradle file whenever you update the app on the playstore? Or can I just leave it as 0.9.9pre until we do the first public release? 
The next logical version would be 0.9.9. 0.9.91pre would come after 0.9.90 as a "beta" before publishing 0.9.91.
If nothing speaks against it, I would leave it as 0.9.9pre as long as we decide to put up the first version on the play store, which would then be 0.9.9.

**Comment by txmiker** [comment]
OK.. like I say, your call.  thanks

**Comment by vbier** [comment]
I have changed the feature-usage to optional as you found out. Thanks for the pull request.

**Pull request closed without merging**
